name: Deploy Portfolio

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/myportfolio
            cd ~/sameer-portfolio

            echo "Pulling latest code..."
            git pull origin main

            echo "Stopping old container..."
            sudo docker rm -f portfolio || true

            echo "Building new image..."
            sudo docker build -t portfolio .

            echo "Starting new container..."
            sudo docker run -d \
              --name portfolio \
              -p 80:80 \
              portfolio

            echo "Deployment complete!"