name: Deploy Portfolio

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            script: |
              echo "WHO AM I?"
              whoami

              echo "WHERE AM I?"
              pwd

              echo "HOME:"
              echo "$HOME"

              echo "CONTENTS OF HOME:"
              ls -la ~

              echo "GOING TO REPO..."
              cd /home/ec2-user/sameer-portfolio

              echo "CURRENT DIRECTORY:"
              pwd

              echo "GIT STATUS:"
              git status

              echo "GIT REMOTE:"
              git remote -v

              echo "PULLING..."
              git pull origin main

              echo "LATEST COMMIT:"
              git log -1 --oneline